import crypto from "crypto";

const PG_IDENTIFIER_MAX = 63;

/**
 * Generate a cryptographically secure random password.
 */
export function generatePassword(length = 24): string {
  return crypto.randomBytes(length).toString("base64url").slice(0, length);
}

/**
 * Convert an org slug to a safe PostgreSQL identifier.
 * Replaces hyphens with underscores, strips invalid chars,
 * prefixes with "org_", and truncates to 63 chars.
 */
export function sanitizeIdentifier(slug: string): string {
  const cleaned = slug.replace(/-/g, "_").replace(/[^a-z0-9_]/g, "");
  const name = `org_${cleaned}`;
  return name.slice(0, PG_IDENTIFIER_MAX);
}

/**
 * Provision a new PostgreSQL database and user for an organization
 * on the shared platform instance.
 *
 * Idempotent — safe to call if the database/user already exists.
 * On re-provision, the password is updated to match the returned value.
 */
export async function provisionDatabase(
  orgSlug: string
): Promise<{ database: string; username: string; password: string }> {
  const adminUrl = process.env.PLATFORM_PG_ADMIN_URL;
  if (!adminUrl) {
    throw new Error(
      "PLATFORM_PG_ADMIN_URL is not set — cannot provision built-in PostgreSQL"
    );
  }

  const { default: pg } = await import("pg");

  const database = sanitizeIdentifier(orgSlug);
  const username = sanitizeIdentifier(orgSlug);
  const password = generatePassword();

  const client = new pg.Client({ connectionString: adminUrl });
  try {
    await client.connect();

    // Create role (idempotent)
    const roleExists = await client.query(
      "SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = $1",
      [username]
    );
    if (roleExists.rowCount === 0) {
      // Cannot parameterise identifiers/passwords in CREATE ROLE,
      // but username is sanitised and password is generated by us.
      await client.query(
        `CREATE ROLE "${username}" WITH LOGIN PASSWORD '${password}'`
      );
    } else {
      // Update password so stored credential always matches
      await client.query(
        `ALTER ROLE "${username}" WITH PASSWORD '${password}'`
      );
    }

    // Create database (idempotent)
    const dbExists = await client.query(
      "SELECT 1 FROM pg_database WHERE datname = $1",
      [database]
    );
    if (dbExists.rowCount === 0) {
      await client.query(`CREATE DATABASE "${database}" OWNER "${username}"`);
    } else {
      // Ensure ownership
      await client.query(`ALTER DATABASE "${database}" OWNER TO "${username}"`);
    }

    // Grant privileges
    await client.query(
      `GRANT ALL PRIVILEGES ON DATABASE "${database}" TO "${username}"`
    );

    return { database, username, password };
  } finally {
    await client.end().catch(() => {});
  }
}
